server:
  port: 9998
  servlet:
    context-path: /user-server
spring:
  freemarker:
    checkTemplateLocation: false
  mvc:
    servlet:
      load-on-startup: 1
  user:
    oauth:
      clientId: fort
      clientSecret: j1d1sec.c0m
      checkTokenUrl: http://dev.server:8080/user-oauth2/oauth/check_token
    server:
      datasource:
        url: jdbc:mysql://dev.server:3306/new_fort?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
        username: fort
        password: Cl0vdsec.mysql
        driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:log4j2.xml        